{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterWide -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-exporter.fullname" . }}
  labels:
{{ include "helm-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - watch
  - list
{{- else -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
{{- end -}}
{{- end -}}
