{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterWide -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-exporter.fullname" . }}
  labels:
{{ include "helm-exporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm-exporter.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- else -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm-exporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "helm-exporter.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "helm-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
